# Generated by Django 4.0.4 on 2022-06-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_commentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentarios',
            new_name='Comentarios',
        ),
    ]
