# Generated by Django 4.0.4 on 2022-06-30 02:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0010_alter_comentarios_texto_alter_post_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Valoracion',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(default='images/avatar.png', null=True, upload_to='media/images/'),
        ),
    ]
