# Generated by Django 4.0.4 on 2022-06-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0011_delete_valoracion_alter_comentarios_texto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
    ]
