# Generated by Django 4.0.4 on 2022-07-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(default='avatar.png', null=True, upload_to='images/'),
        ),
    ]
